### ISSUE TITLE
Error when viewing a memory

### ISSUE THREAD

**Issue by uskudarli** [enshkn/BOUN-SWE-573-SPRING-23#69]
While viewing a memory I got the following error:

```bash

Request Method: POST
Request URL: http://3.88.53.150/memory/8/

Django Version: 4.1.7
Python Version: 3.10.10
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'base.apps.BaseConfig',
 'rest_framework',
 'ckeditor']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/base/views.py", line 89, in memory
    message = Message.objects.create(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 669, in create
    obj = self.model(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py", line 237, in __set__
    raise ValueError(

Exception Type: ValueError at /memory/8/
Exception Value: Cannot assign "<SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f7d90725990>>": "Message.user" must be a "User" instance.


```

**Comment by enshkn** [comment]
Hocam, I think it is an error due to the guest who is not logged in the system commenting on a post, I will make the necessary edit and add the necessary explanation. Kind regards.

**Comment by enshkn** [comment]
the problem is here; 
base/templates/base/memory.html , line: 150-155 'de yer alan division: 
<div class="memory__message" style="position:relative; top:-50px">
            <form action="" method="POST">
                {% csrf_token %}
                <input name="comment-body" placeholder="Write your message here..." /></form>
          </div>

will be closed with

{% if user.is_authenticated %}
{% endif %}.

Thus, only logged in users will be able to see the message writing section.
